import type { Driver, ApprovalQueueItem } from './types';

export const MOCK_DRIVERS: Driver[] = [
  {
    id: 'drv-8821',
    customId: '#DRV-8821',
    name: 'Vikram Sharma',
    phone: '+91 98201 44521',
    email: 'vikram.sharma@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    vendorId: 'vnd-101',
    vendorName: 'Sahani Logistics & Fleet',
    vendorCompany: 'Sahani Travels Pvt Ltd',
    assignedVehicle: 'MH-01-EE-9901',
    vehicleModel: 'Tata Intra V30',
    vehicleType: 'Heavy Vehicle',
    city: 'Mumbai',
    state: 'Maharashtra',
    hub: 'Andheri Central Hub',
    experienceYears: 12,
    category: 'Heavy Vehicle Driver • 12 Years Exp.',
    bloodGroup: 'O+',
    dateOfBirth: '1988-05-14',
    joiningDate: '2026-08-20',
    appliedDate: 'Applied 2 hours ago',
    onlineStatus: 'online',
    kycStatus: 'pending',
    backgroundCheckPassed: true,
    rating: 4.85,
    totalTrips: 1420,
    acceptanceRate: 96,
    cancellationRate: 1.8,
    dailyEarnings: 3450,
    emergencyContact: {
      name: 'Sunita Sharma',
      phone: '+91 98201 99882',
      relation: 'Spouse',
    },
    bankDetails: {
      accountHolder: 'Vikram Sharma',
      accountNumber: '409281729012',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0001244',
    },
    documents: {
      drivingLicense: {
        status: 'expiring_soon',
        label: 'Driving License (DL)',
        documentNumber: 'MH-01-20120008451',
        expiryDate: '2026-11-30',
        fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
        fileName: 'dl_vikram_sharma.pdf',
        fileSize: '1.8 MB',
        verifiedApi: true,
      },
      aadhaarCard: {
        status: 'verified',
        label: 'Aadhaar Card',
        documentNumber: '**** **** 1029',
        fileUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        fileName: 'aadhaar_vikram_sharma.pdf',
        fileSize: '2.1 MB',
        verifiedApi: true,
      },
      panCard: {
        status: 'verified',
        label: 'PAN Card',
        documentNumber: 'ASWPS****M',
        fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
        fileName: 'pan_vikram_sharma.jpg',
        fileSize: '1.2 MB',
        verifiedApi: true,
      },
      medicalFitness: {
        status: 'awaiting_upload',
        label: 'Medical Fitness Cert.',
        uploadDate: 'Uploaded: 24 May 2024',
        fileName: 'medical_fitness.pdf',
        fileSize: '950 KB',
      },
    },
  },
  {
    id: 'drv-8819',
    customId: '#DRV-8819',
    name: 'Amitabh Bachchan',
    phone: '+91 98202 88410',
    email: 'amitabh.b@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    vendorId: 'vnd-102',
    vendorName: 'Apex Mobility Solutions',
    vendorCompany: 'Apex Fleet Corp',
    assignedVehicle: 'MH-02-CP-8822',
    vehicleModel: 'Maruti Suzuki Dzire Tour',
    vehicleType: 'Sedan',
    city: 'Mumbai',
    state: 'Maharashtra',
    hub: 'BKC Business Yard',
    experienceYears: 8,
    category: 'Commercial Sedan Driver • 8 Years Exp.',
    bloodGroup: 'B+',
    dateOfBirth: '1985-11-20',
    joiningDate: '2026-08-18',
    appliedDate: 'Applied 2 days ago',
    onlineStatus: 'online',
    kycStatus: 'pending',
    backgroundCheckPassed: true,
    rating: 4.92,
    totalTrips: 980,
    acceptanceRate: 98,
    cancellationRate: 1.2,
    dailyEarnings: 4120,
    emergencyContact: {
      name: 'Jaya B',
      phone: '+91 98202 77112',
      relation: 'Spouse',
    },
    bankDetails: {
      accountHolder: 'Amitabh Bachchan',
      accountNumber: '50100293849102',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0000844',
    },
    documents: {
      drivingLicense: {
        status: 'valid',
        label: 'Driving License (DL)',
        documentNumber: 'MH-02-20160099812',
        expiryDate: '2029-04-15',
        fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
        fileName: 'dl_amitabh.pdf',
        fileSize: '1.4 MB',
        verifiedApi: true,
      },
      aadhaarCard: {
        status: 'verified',
        label: 'Aadhaar Card',
        documentNumber: '**** **** 4892',
        fileUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        fileName: 'aadhaar_amitabh.pdf',
        fileSize: '1.9 MB',
        verifiedApi: true,
      },
      panCard: {
        status: 'verified',
        label: 'PAN Card',
        documentNumber: 'BKPB****R',
        fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
        fileName: 'pan_amitabh.jpg',
        fileSize: '1.1 MB',
        verifiedApi: true,
      },
      medicalFitness: {
        status: 'verified',
        label: 'Medical Fitness Cert.',
        uploadDate: 'Uploaded: 12 Aug 2026',
        fileName: 'medical_fitness_amitabh.pdf',
        fileSize: '1.2 MB',
      },
    },
  },
  {
    id: 'drv-7401',
    customId: '#DRV-7401',
    name: 'Rajesh Patel',
    phone: '+91 97123 44556',
    email: 'rajesh.patel@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    vendorId: 'vnd-101',
    vendorName: 'Sahani Logistics & Fleet',
    vendorCompany: 'Sahani Travels Pvt Ltd',
    assignedVehicle: 'MH-12-QX-4029',
    vehicleModel: 'Eicher 10.75 E2 Plus',
    vehicleType: 'Heavy Vehicle',
    city: 'Pune',
    state: 'Maharashtra',
    hub: 'Pune Logistics Hub',
    experienceYears: 6,
    category: 'Commercial Truck Driver • 6 Years Exp.',
    bloodGroup: 'A+',
    dateOfBirth: '1992-04-10',
    joiningDate: '2026-06-15',
    appliedDate: 'Applied 1 week ago',
    onlineStatus: 'on_trip',
    kycStatus: 'approved',
    backgroundCheckPassed: true,
    rating: 4.78,
    totalTrips: 2150,
    acceptanceRate: 94,
    cancellationRate: 2.1,
    dailyEarnings: 2980,
    emergencyContact: {
      name: 'Ramesh Patel',
      phone: '+91 97123 11223',
      relation: 'Brother',
    },
    bankDetails: {
      accountHolder: 'Rajesh Patel',
      accountNumber: '302918273645',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0004521',
    },
    documents: {
      drivingLicense: {
        status: 'valid',
        label: 'Driving License (DL)',
        documentNumber: 'MH-12-20180044123',
        expiryDate: '2031-08-20',
        fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
        fileName: 'dl_rajesh.pdf',
        fileSize: '1.5 MB',
        verifiedApi: true,
      },
      aadhaarCard: {
        status: 'verified',
        label: 'Aadhaar Card',
        documentNumber: '**** **** 7741',
        fileUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        fileName: 'aadhaar_rajesh.pdf',
        fileSize: '1.7 MB',
        verifiedApi: true,
      },
      panCard: {
        status: 'verified',
        label: 'PAN Card',
        documentNumber: 'CGSP****K',
        fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
        fileName: 'pan_rajesh.jpg',
        fileSize: '980 KB',
        verifiedApi: true,
      },
      medicalFitness: {
        status: 'verified',
        label: 'Medical Fitness Cert.',
        uploadDate: 'Uploaded: 10 Jan 2026',
        fileName: 'medical_fitness_rajesh.pdf',
        fileSize: '1.1 MB',
      },
    },
  },
  {
    id: 'drv-6302',
    customId: '#DRV-6302',
    name: 'Suresh Yadav',
    phone: '+91 98334 11299',
    email: 'suresh.yadav@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
    vendorId: 'vnd-103',
    vendorName: 'Metro Ride Express',
    vendorCompany: 'Metro Cabs India',
    assignedVehicle: 'MH-04-AZ-2030',
    vehicleModel: 'Hyundai Aura CNG',
    vehicleType: 'Sedan',
    city: 'Thane',
    state: 'Maharashtra',
    hub: 'Thane Transport Yard',
    experienceYears: 4,
    category: 'City Cab Driver • 4 Years Exp.',
    bloodGroup: 'O-',
    dateOfBirth: '1995-08-25',
    joiningDate: '2026-07-01',
    appliedDate: 'Applied 3 weeks ago',
    onlineStatus: 'offline',
    kycStatus: 'approved',
    backgroundCheckPassed: true,
    rating: 4.65,
    totalTrips: 840,
    acceptanceRate: 91,
    cancellationRate: 3.4,
    dailyEarnings: 1850,
    emergencyContact: {
      name: 'Geeta Yadav',
      phone: '+91 98334 99881',
      relation: 'Mother',
    },
    bankDetails: {
      accountHolder: 'Suresh Yadav',
      accountNumber: '918273645012',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0001092',
    },
    documents: {
      drivingLicense: {
        status: 'valid',
        label: 'Driving License (DL)',
        documentNumber: 'MH-04-20200019283',
        expiryDate: '2035-12-10',
        fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
        fileName: 'dl_suresh.pdf',
        fileSize: '1.6 MB',
        verifiedApi: true,
      },
      aadhaarCard: {
        status: 'verified',
        label: 'Aadhaar Card',
        documentNumber: '**** **** 9012',
        fileUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        fileName: 'aadhaar_suresh.pdf',
        fileSize: '2.0 MB',
        verifiedApi: true,
      },
      panCard: {
        status: 'verified',
        label: 'PAN Card',
        documentNumber: 'ASYPK****D',
        fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
        fileName: 'pan_suresh.jpg',
        fileSize: '1.3 MB',
        verifiedApi: true,
      },
      medicalFitness: {
        status: 'verified',
        label: 'Medical Fitness Cert.',
        uploadDate: 'Uploaded: 15 Jun 2026',
        fileName: 'medical_suresh.pdf',
        fileSize: '1.0 MB',
      },
    },
  },
  {
    id: 'drv-5190',
    customId: '#DRV-5190',
    name: 'Anjali Shinde',
    phone: '+91 98209 88122',
    email: 'anjali.shinde@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    vendorId: 'vnd-102',
    vendorName: 'Apex Mobility Solutions',
    vendorCompany: 'Apex Fleet Corp',
    assignedVehicle: 'MH-01-EE-3344',
    vehicleModel: 'Tata Tigor EV',
    vehicleType: 'Electric',
    city: 'Mumbai',
    state: 'Maharashtra',
    hub: 'Navi Mumbai Central Hub',
    experienceYears: 5,
    category: 'EV Fleet Specialist • 5 Years Exp.',
    bloodGroup: 'AB+',
    dateOfBirth: '1993-02-17',
    joiningDate: '2026-05-10',
    appliedDate: 'Applied 1 month ago',
    onlineStatus: 'online',
    kycStatus: 'approved',
    backgroundCheckPassed: true,
    rating: 4.96,
    totalTrips: 1890,
    acceptanceRate: 99,
    cancellationRate: 0.5,
    dailyEarnings: 4800,
    emergencyContact: {
      name: 'Deepak Shinde',
      phone: '+91 98209 11990',
      relation: 'Spouse',
    },
    bankDetails: {
      accountHolder: 'Anjali Shinde',
      accountNumber: '109283746519',
      bankName: 'Kotak Mahindra Bank',
      ifscCode: 'KKBK0000451',
    },
    documents: {
      drivingLicense: {
        status: 'valid',
        label: 'Driving License (DL)',
        documentNumber: 'MH-01-20190088192',
        expiryDate: '2034-03-01',
        fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
        fileName: 'dl_anjali.pdf',
        fileSize: '1.4 MB',
        verifiedApi: true,
      },
      aadhaarCard: {
        status: 'verified',
        label: 'Aadhaar Card',
        documentNumber: '**** **** 3319',
        fileUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        fileName: 'aadhaar_anjali.pdf',
        fileSize: '1.8 MB',
        verifiedApi: true,
      },
      panCard: {
        status: 'verified',
        label: 'PAN Card',
        documentNumber: 'AQPSH****N',
        fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
        fileName: 'pan_anjali.jpg',
        fileSize: '1.0 MB',
        verifiedApi: true,
      },
      medicalFitness: {
        status: 'verified',
        label: 'Medical Fitness Cert.',
        uploadDate: 'Uploaded: 05 May 2026',
        fileName: 'medical_anjali.pdf',
        fileSize: '1.3 MB',
      },
    },
  },
  {
    id: 'drv-4091',
    customId: '#DRV-4091',
    name: 'Manoj Kumar',
    phone: '+91 98111 22334',
    email: 'manoj.kumar@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    vendorId: 'vnd-104',
    vendorName: 'Urban Fleet Logistics',
    vendorCompany: 'Urban Transport Ltd',
    assignedVehicle: 'DL-01-AA-9988',
    vehicleModel: 'Maruti Ertiga Hybrid',
    vehicleType: 'SUV',
    city: 'Delhi NCR',
    state: 'Delhi',
    hub: 'IGI Airport Hub',
    experienceYears: 7,
    category: 'Airport Transfer Driver • 7 Years Exp.',
    bloodGroup: 'B-',
    dateOfBirth: '1990-09-12',
    joiningDate: '2026-08-01',
    appliedDate: 'Applied 3 days ago',
    onlineStatus: 'busy',
    kycStatus: 'suspended',
    backgroundCheckPassed: false,
    rating: 4.12,
    totalTrips: 620,
    acceptanceRate: 82,
    cancellationRate: 8.5,
    dailyEarnings: 1200,
    emergencyContact: {
      name: 'Sunil Kumar',
      phone: '+91 98111 88990',
      relation: 'Father',
    },
    bankDetails: {
      accountHolder: 'Manoj Kumar',
      accountNumber: '601928374619',
      bankName: 'Punjab National Bank',
      ifscCode: 'PUNB0001928',
    },
    documents: {
      drivingLicense: {
        status: 'expired',
        label: 'Driving License (DL)',
        documentNumber: 'DL-01-20150019283',
        expiryDate: '2026-07-30',
        fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80',
        fileName: 'dl_manoj.pdf',
        fileSize: '1.2 MB',
        verifiedApi: false,
      },
      aadhaarCard: {
        status: 'verified',
        label: 'Aadhaar Card',
        documentNumber: '**** **** 6192',
        fileUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        fileName: 'aadhaar_manoj.pdf',
        fileSize: '1.7 MB',
        verifiedApi: true,
      },
      panCard: {
        status: 'rejected',
        label: 'PAN Card',
        documentNumber: 'ALPKM****T',
        fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
        fileName: 'pan_manoj.jpg',
        fileSize: '950 KB',
        verifiedApi: false,
      },
      medicalFitness: {
        status: 'pending',
        label: 'Medical Fitness Cert.',
        uploadDate: 'Uploaded: 01 Aug 2026',
        fileName: 'medical_manoj.pdf',
        fileSize: '1.1 MB',
      },
    },
  },
];

export const MOCK_APPROVAL_QUEUE: ApprovalQueueItem[] = [
  {
    id: 'app-01',
    type: 'driver',
    regId: '#DRV-8821',
    title: 'Vikram Sharma',
    subtitle: 'Heavy Vehicle Driver • 12 Years Exp.',
    appliedTime: 'Applied 2 hours ago',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    vendorName: 'Sahani Logistics & Fleet',
    status: 'pending',
    driverData: MOCK_DRIVERS[0],
  },
  {
    id: 'app-02',
    type: 'vehicle',
    regId: 'MH-12-QX-4029',
    title: 'Eicher 10.75 E2 Plus',
    subtitle: 'Commercial Heavy Goods Truck',
    appliedTime: 'Applied 5 hours ago',
    vendorName: 'Sahani Logistics & Fleet',
    status: 'pending',
  },
  {
    id: 'app-03',
    type: 'vehicle',
    regId: 'KA-01-EE-9901',
    title: 'Tata Intra V30',
    subtitle: 'Commercial Light Delivery Van',
    appliedTime: 'Applied 1 day ago',
    vendorName: 'Apex Mobility Solutions',
    status: 'pending',
  },
  {
    id: 'app-04',
    type: 'driver',
    regId: '#DRV-8819',
    title: 'Amitabh Bachchan',
    subtitle: 'Commercial Sedan Driver • 8 Years Exp.',
    appliedTime: 'Applied 2 days ago',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    vendorName: 'Apex Mobility Solutions',
    status: 'pending',
    driverData: MOCK_DRIVERS[1],
  },
  {
    id: 'app-05',
    type: 'driver',
    regId: '#DRV-4091',
    title: 'Manoj Kumar',
    subtitle: 'Airport Transfer Driver • 7 Years Exp.',
    appliedTime: 'Applied 3 days ago',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    vendorName: 'Urban Fleet Logistics',
    status: 'pending',
    driverData: MOCK_DRIVERS[5],
  },
];
